modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/Swirtzly/Weeping-Angels/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod"
logoFile="logo.png"
credits="Ed, Ford, Myself, Rolf, Nictogen, Lukas, ShadowBolt"
authors="Swirtzly"
[[mods]]
modId="weeping_angels"
version="3.0.0"
displayName="Weeping Angels"
updateJSONURL="https://raw.githubusercontent.com/WhoCraft/Weeping-Angels/1.14/update.json" #optional
description='''
Mod that adds the terrifying Weeping Angel creatues to Minecraft || Originally made for ModJam 5'''
[[dependencies.weeping_angels]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.weeping_angels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.weeping_angels]]
    modId="tardis"
    mandatory=false
    versionRange="[1.2.0,)"
    ordering="AFTER"
    side="BOTH"